version: "3"
services:
  browserless:
    image: ghcr.io/browserless/chrome
    restart: always
    ports:
      - 3003:3000
    environment:
      - TZ=Europe/Berlin

  screencurl:
    image: ghcr.io/bitmorse/screencurl
    restart: always
    ports:
      - 9898:9898
    environment:
      - TZ=Europe/Berlin
      - BROWSERLESS_URL=http://browserless:3000
      #- TOKENS=comma,separated,list,of,tokens
      - DEFAULT_VIEWPORT_WIDTH=1920
      - DEFAULT_VIEWPORT_HEIGHT=1080
      - WAIT_FOR_LOAD=networkidle0 # Strictest option - waits until there are 0 network connections for 500ms
    depends_on:
      - browserless
networks: {}